### ISSUE TITLE
Hex value error after updating to Version 1.x-2.1.0

### ISSUE THREAD

**Issue by Acertijo** [backdrop-contrib/mosaic_grid#14] opened 2020-02-02 13:18 UTC
Hi, right after update to 1.x-2.1.0, all the pages using Mosaic are in maintenance mode with the text 
**

> '' is not a valid hex value.

**
all the rest of the site works fine, for now i returned to 1.x-2.0.2 and works again

**Comment by korontari** [comment] 2020-02-02 14:13
Hi Acertijo,
Thank you for reporting this. I got this bug and working on it right now. The issue is with updating the module's configuration file. I should be able to release a fix soon.

**Comment by korontari** [comment] 2020-02-03 12:20
Hi @Acertijo,

Do you mind testing this [PR](https://github.com/backdrop-contrib/mosaic_grid/pull/15) and letting me know if it works for you?

**Comment by korontari** [comment] 2020-02-05 11:51
Hi @Acertijo,

The new version that contains this bug fix has been released. Could you try to update the module and let me know if everything works fine in your environment?

**Comment by Acertijo** [comment] 2020-02-06 20:32
Hi korontari, it works fine now, thanks

**Comment by korontari** [comment] 2020-02-09 15:04
Thank you, @Acertijo!

**Closed as completed by korontari** 2020-02-09 15:04 UTC
