### ISSUE TITLE
Mosiac display breaks in layout that is not full width of page

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/mosaic_grid#6] opened 2019-10-10 01:03 UTC
If I create a mosaic grid and display it in a region that is the full width of the page, it seems to display fine. But, I I change layout templates to one in which the content region does not extend all the way across the page, the layout breaks. 

If the mosiac starts at full width, it works fine at smaller screen sizes. But, if you put the same display into a region that is only 75% the width of the page, it breaks. 

It's as if the layout is not adjusting for the width of the region, rather it assume it has the entire page width and if the region is smaller, it breaks. 

Basis theme - Boxton layout template - width 100%
![Test___Triplo](https://user-images.githubusercontent.com/3144571/66530986-b9550f00-eacf-11e9-8362-f682278697dc.png)

Basis theme - Moscone Full layout template - width 75%
![Test___Triplo](https://user-images.githubusercontent.com/3144571/66530926-890d7080-eacf-11e9-82bd-d2c743c3e402.png)

**Comment by korontari** [comment] 2019-10-10 10:13
@stpaultim , thank you for your information! I tried to reproduce the issue as you described it but didn't find 'Moscone Full' template. Did you mean some other 'Moscone' layout? I did have tested it in different layouts(with Basis theme) and in my case it worked fine with all Moscone templates except for the Moscone Hero.  Also I noticed that when I apply a different theme (Borg, Bootstrap Lite) it breaks on layouts that worked fine with Basis (for instance Boxton - Bootstrap Lite combination).  So the case looks quite tricky for me to solve quickly. I will explore it in depth. Meanwhile if you have more observations concerning the broken grid I would appreciate if you post them here.

**Comment by korontari** [comment] 2019-10-10 14:39
@stpaultim, could you try [this version](https://github.com/backdrop-contrib/mosaic_grid/tree/1.x-1.0.2) and check if you still have issues with grid display broken? (Please make sure to clean cache first).

**Comment by stpaultim** [comment] 2019-10-10 20:45
OK. I have not tested your new version yet. 

Sorry, I might have used a contrib layout template for my test (example). However, I don't think the problem was specific to that template. I believe it effected ANY template in which the content does not stretch all the way across the page. Or, any situation when the content block is in a region with more than one block/column.

I will test your new version later and see if that solves the problem and/or provide better instruction on how to recreate the issue if it still exists. 

NOTE: I do not need a fix to this issue right away. I just noticed this problem while testing, but I do appreciate your quick response.

**Comment by stpaultim** [comment] 2019-10-11 04:58
I think that this might have something to do with browser caching or something. If I keep changing the size of the mosiac and then trying it in different layout templates, it ocassionally will break. When it breaks, clearing the caches does not fix it. But, if I keep playing with it eventually the layout seems to work again and once it works, it's fine until I change the Maximum row again. 

This is happening to me with Chrome. I've not tested in other browsers. 

Since I can not provide reliable steps to reproduce and if no one else is having this problem, you can probably ignore it and/or wait and see if anyone else has problems.

**Comment by korontari** [comment] 2019-10-11 12:58
@stpaultim, thank you for your feedback! I understand that there is no pressure on this, thank you for your note. I am just concerned that the core functionality is quite unstable and I myself as a user would be quite upset with it. After having been playing around with the module for quite a long period of time I find more and more occasions when the grid breaks apart. For instance it breaks when user scales a page in browser.  I tend to think the issue is with the code inside the jquery plugin. I did some quick tests using a different plugin with similar functionality and it looks quite promising and much more stable. Once I have some spare time I will try to make a new version with it and test it.

**Comment by stpaultim** [comment] 2019-10-11 19:27
Yes, I've also noticed the issue with how scaling the page affecting the layout. In fact, I think that in some cases, scaling the page has helped fix the weird behavior I was seeing. All which does suggest a lack of stability/reliability. 

To be clear, I'm intrigued by this module partly because I was curious if it would have been useful for the mosiac I built for this website: https://www.riverton.org 

I don't think it would have been, since that was a planned and structured mosaic. The strength of this module seems to be creating new mosaics out of random or changing images. 

I don't have an immediate use for this module, I'm just interested in it for the future. Thanks for working on it. I'll continue to keep an eye on it and help test as needed.

**Comment by korontari** [comment] 2019-10-12 14:27
Thank you for your support @stpaultim! I have attached a new plugin and made a version with it: https://github.com/backdrop-contrib/mosaic_grid/tree/1.x-2.0.0  Would you mind testing it when you have some time?

BTW, I really liked the design of www.riverton.org. Very well done! Offtopic question: did you make a theme for this site from scratch or did you modified Basis or other existing theme? Just curious about the workflow.

**Comment by stpaultim** [comment] 2019-10-13 06:47
Thank you for working on this module. 

Riverton is a sub-theme of Basis with lots of custom CSS. We used SASS to compile our CSS.

**Comment by stpaultim** [comment] 2019-10-13 06:57
Also - I just did a quick test of your 2.0 branch and it does seem to be more stable. I like it! 

I did not test is very hard, I will try to play with it more later, but first impression is very good. This version does not break for smaller column layouts (at first glance).

**Comment by korontari** [comment] 2019-10-15 11:32
@stpaultim, thank you for testing! If you have a chance to play with it more that would be great. I will then be more confident tagging a release. So far during testing of a new plugin I saw only one occurrence when the grid wasn't built correctly.

**Comment by korontari** [comment] 2019-10-17 11:24
I will close this issue for now. If you notice this or related bugs happening again feel free to reopen it.

**Closed as completed by korontari** 2019-10-17 11:24 UTC
